spring:
  application:
    name: cicd-dashboard

  datasource:
    url: jdbc:postgresql://postgres:5432/cicd_dashboard
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

github:
  api:
    base-url: ${GITHUB_API_BASE_URL:https://api.github.com}
    token: ${GITHUB_TOKEN:your_github_personal_access_token_here}
    timeout: ${GITHUB_API_TIMEOUT:10000}

scheduler:
  enabled: ${SCHEDULER_ENABLED:true}
  github-sync-rate: ${SCHEDULER_GITHUB_SYNC_RATE:300000}
  repositories: []  # Configure via environment or mount config file

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.peraton.cicd: ${LOGGING_LEVEL_COM_PERATON_CICD:INFO}
    org.springframework.web: INFO
    org.hibernate: WARN
    org.springframework.scheduling: INFO
  file:
    name: /app/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
