spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cicd_dashboard_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.peraton.cicd: DEBUG
    org.springframework.web: DEBUG
