spring:
  application:
    name: cicd-dashboard

  datasource:
    url: jdbc:postgresql://localhost:5432/cicd_dashboard
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN:your_github_personal_access_token_here}
    timeout: 10000

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

scheduler:
  enabled: true
  github-sync-rate: 300000  # 5 minutes in milliseconds
  repositories:
    # Example configuration - uncomment and update with your repositories
    # - id: 1
    #   owner: microsoft
    #   repo: vscode
    #   enabled: true
    # - id: 2
    #   owner: spring-projects
    #   repo: spring-boot
    #   enabled: true

logging:
  level:
    com.peraton.cicd: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.scheduling: INFO
